### ISSUE TITLE
importmembers: data error in members file gives no error message

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#155]
When the member file has bad dates (e.g., mm/dd/yyyy), the user does not get an error message when the following exception happens.

    Message type:       ERROR
    Location:           /var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py:1423
    Module:             app
    Function:           log_exception
    Time:               2015-05-05 12:38:12,474

    Message:

    Exception on /_importmembers [POST]

    Traceback (most recent call last):
      File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
        return func(*args, **kwargs)
      File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/views.py", line 84, in view
        return self.dispatch_request(*args, **kwargs)
      File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
        return meth(*args, **kwargs)
      File "/home/content/89/11476389/html/scoretility/rrwebapp/member.py", line 390, in post
        age = timeu.age(asof,tYmd.asc2dt(thisdob))
      File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/loutilities-0.10.1-py2.7.egg/loutilities/timeu.py", line 222, in asc2dt
        return datetime.datetime.strptime(asctime,self.ascformat)
      File "/usr/local/lib/python2.7/_strptime.py", line 325, in _strptime
        (data_string, format))
    ValueError: time data '1/30/1968' does not match format '%Y-%m-%d'

**Comment by louking** [comment]
[members-silent-error-from-jenny.csv | uploaded via ZenHub](https://files.zenhub.io/559d05ceaffd3437614ae771)
