### ISSUE TITLE
possibly seeing some caching issues

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#157]
* reediting tabulated results gets error on confirm, that result not found

        Message type:       ERROR
        Location:           /home/content/89/11476389/html/scoretility/rrwebapp/results.py:901
        Module:             results
        Function:           post
        Time:               2015-06-11 08:34:41,890

        Message:

        Unexpected Error: result id 28601 not found

* can't log out -- getting key error on username

        Message type:       ERROR
        Location:           /var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py:1423
        Module:             app
        Function:           log_exception
        Time:               2015-06-14 06:40:22,557

        Message:

        Exception on /logout [GET]
        
        Traceback (most recent call last):
          File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
            response = self.full_dispatch_request()
          File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
            rv = self.handle_user_exception(e)
          File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
            reraise(exc_type, exc_value, tb)
          File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
            rv = self.dispatch_request()
          File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
            return self.view_functions[rule.endpoint](**req.view_args)
          File "/home/content/89/11476389/html/scoretility/rrwebapp/login.py", line 157, in logout
            app.logger.debug("logging out user '<unknown>'".format(flask.session['user_name']))
          File "/var/chroot/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/werkzeug/local.py", line 368, in <lambda>
            __getitem__ = lambda x, i: x._get_current_object()[i]

**Comment by louking** [comment]
See these for ideas

* http://stackoverflow.com/questions/23112316/using-flask-how-do-i-modify-the-cache-control-header-for-all-output
* http://arusahni.net/blog/2014/03/flask-nocache.html
