### ISSUE TITLE
exception in results view

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#210]
Saw this exception 2016-05-10 10:37am EDT / 7:37am MST

            Message type:       ERROR
            Location:           /home/content/89/11476389/html/scoretility/rrwebapp/results.py:1454
            Module:             results
            Function:           post
            Time:               2016-05-10 07:37:05,999
    
            Message:
    
            Traceback (most recent call last):
      File "/home/content/89/11476389/html/scoretility/rrwebapp/results.py", line 1421, in post
        fileresult = rr.next()
      File "/home/content/89/11476389/html/scoretility/rrwebapp/raceresults.py", line 350, in next
        if result['name'] is None or result['name'][0] in '=-/!':
    IndexError: string index out of range

**Comment by louking** [comment]
Probably better to handle the exception then let it bubble up to the email transmitter

Maybe error check the file and handle more gracefully.
