### ISSUE TITLE
importresults: large file hangs

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#211]
From @runjdon: 

Lou, I'm stumped. I just can't get this file to upload. I'm not getting any error message, it just hangs at the "loading" screen. No timeout message, and other than the moving "loading" bar, there is no indication of any processing. I've tried uploading chunks of the file at a time, and I've been able to get most of it. But then I'll upload a larger chunk and it just hangs on me, and I don't know why. Can you take a look and see if you can find something I might be missing?

[frederickhalf2016.zip](https://github.com/louking/rrwebapp/files/257890/frederickhalf2016.zip)

**Comment by louking** [comment]
I suspect this is some timeout on the async ajax request, and poor error handling after the timeout

**Comment by louking** [comment]
Through developer tools discovered apache is returning 500 internal server error after 40 seconds (need to handle error gracefully).

I searched for "apache 40 second server error" and found https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html and searched within page for 40 and found https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgidiotimeout

Used FcgidIOTimeout 60 in the apache configuration file on sandbox, and the behavior changed, so this is the parameter which is causing the problem.

I don't think I can change this parameter in the .htaccess file on godaddy, so I need to figure out how to multithread my application and poll status of the import, which doesn't look easy on godaddy.

I might be hosed on this one because of the godaddy limitations.

**Comment by louking** [comment]
Need to find pure python solution because can't install (e.g.) Celery or RabbitMQ on godaddy

- http://stackoverflow.com/questions/11158121/non-message-queue-simple-long-polling-in-python-and-flask
- http://stackoverflow.com/questions/29517223/long-polling-in-python-with-flask

or maybe server push? this wouldn't require threading

- http://stackoverflow.com/questions/12232304/how-to-implement-server-push-in-flask-framework

**Comment by louking** [comment]
Determined can't use rabbitmq on godaddy. They don't have it internally and they block the port for the cloud rabbitmq, and are not willing to change the configuration.

While there are a lot of reasons to move from godaddy (e.g., to digitalocean), it would be a hassle so looking for other solutions.

Celery works with sqlalchemy broker, although that is experimental.

Tried using sqlite, but got an error creating a semaphore (see below). http://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied indicates this is a problem with /dev/shm permissions, which cannot be changed.

    [2016-05-26 14:25:04,140: ERROR/MainProcess] Unrecoverable error: OSError(13, 'Permission denied')
    Traceback (most recent call last):
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
        self.blueprint.start(self)
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
        step.start(parent)
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
        return self.obj.start()
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/celery/concurrency/base.py", line 131, in start
        self.on_start()
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 119, in on_start
        **self.options)
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/billiard/pool.py", line 931, in __init__
        self._setup_queues()
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/billiard/pool.py", line 1274, in _setup_queues
        self._inqueue = SimpleQueue()
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/billiard/queues.py", line 370, in __init__
        self._rlock = Lock()
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/billiard/synchronize.py", line 160, in __init__
        SemLock.__init__(self, SEMAPHORE, 1, 1)
      File "/home/content/89/11476389/devhome/venv/lib/python2.7/site-packages/billiard/synchronize.py", line 72, in __init__
        sl = self._semlock = _billiard.SemLock(kind, value, maxvalue)
    OSError: [Errno 13] Permission denied

**Comment by louking** [comment]
scoretility successfully moved to digitalocean (now scoretility.com), this is now unblocked

**Comment by louking** [comment]
Some random, hopefully helpful links

* http://blog.miguelgrinberg.com/post/using-celery-with-flask
    * see Complex Example: Showing Status Updates and Results
    * http://blog.miguelgrinberg.com/post/celery-and-the-flask-application-factory-pattern
* Celery Security
    * http://docs.celeryproject.org/en/latest/userguide/security.html 
    * http://stackoverflow.com/questions/27070485/initializing-a-worker-with-arguments-using-celery 
* Celery Sqlalchemy
    * http://stackoverflow.com/questions/12044776/how-to-use-flask-sqlalchemy-in-a-celery-task

**Comment by louking** [comment]
Code updated for this fix in the following commits

* 5624e5f make importresults into background task, with progress updates on gui
* be98cc3 celery background task and rrwebapp application running
* f68eb94 working background task and progress updates for import results
* 266a793 importresults: show %age complete in progress bar
* 05931b6 editparticipants: load data from server

**Comment by louking** [comment]
Had to make changes in the following commits to a) handle exceptions in the background task, b) send email on background task exception, and, c) get the communication between apache page handler and background task to work on CentOS

* b32c796 importresultstask: exception should not be Ignored
* cf214b3 importresultstask: debugging production exception
* 26dd0ed importresultstask: debugging exception
* 195b136 importresultstask: handle exception in task gracefully
* b4b5c05 importtaskresults: use correct traceback call for email
* ebec7bb importresults: use appdirs to store temporary upload
* a3ae00c importresults: configure UPLOAD_TEMP_DIR in rrwebapp.cfg
