### ISSUE TITLE
results: search of integer produces exception within sqlalchemy-datatables

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#219]
See below. This may be fixed in a later release of sqlalchemy-datatables

    Message type:       ERROR
          Location:           /var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py:1423
          Module:             app
          Function:           log_exception
          Time:               2016-06-19 23:52:47,341

          Message:

          Exception on /_results [GET]

    Traceback (most recent call last):
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 84, in view
        return self.dispatch_request(*args, **kwargs)
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
        return meth(*args, **kwargs)
      File "/var/www/scoretility.com/rrwebapp/rrwebapp/request.py", line 205, in wrapped_function
        resp = make_response(f(*args, **kwargs))
      File "/var/www/scoretility.com/rrwebapp/rrwebapp/results.py", line 1279, in get
        rowTable = DataTables(request.args, RaceResult, RaceResult.query.filter_by(**resultfilter).join("runner").join("series").filter_by(**seriesfilter).join("race"), columns, dialect='mysql')
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/datatables/__init__.py", line 172, in __init__
        self.run()
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/datatables/__init__.py", line 223, in run
        self.filtering()
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/datatables/__init__.py", line 319, in filtering
        regex = clean_regex(searchValue)
      File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/datatables/__init__.py", line 62, in clean_regex
        ret_regex = ret_regex.replace('\\','')
    AttributeError: 'int' object has no attribute 'replace'

**Comment by louking** [comment]
Fixed in https://github.com/louking/sqlalchemy-datatables/commit/de90a7a04323fa55beb088b5716572040b401fe7 , PR https://github.com/Pegase745/sqlalchemy-datatables/pull/55
