### ISSUE TITLE
rabbitmq: backlog limit exceeded

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#287]
This may have happened because of the following: during results analysis, sandbox server logged me out, so my javascript status update was not running. I'm surprised this causes the queue to build, though, so maybe this wasn't the cause.

Recovered by restarting rabbitmq-server service, then restarting all supervisord celery tasks.

```
        Message type:       ERROR
        Location:           /var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py:1587
        Module:             app
        Function:           log_exception
        Time:               2016-11-22 09:45:58,894

        Message:

        Exception on /resultsanalysisstatus/rest [GET]

Traceback (most recent call last):
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/resultsanalysis.py", line 252, in get
    return self._retrieverows()
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/resultsanalysis.py", line 211, in _retrieverows
    if task.state == 'PENDING':
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/celery/result.py", line 394, in state
    return self._get_task_meta()['status']
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/celery/result.py", line 339, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/celery/backends/amqp.py", line 180, in get_task_meta
    raise self.BacklogLimitExceeded(task_id)
BacklogLimitExceeded: 82fdd365-a989-45ba-bb78-a456f16b70b6
```

**Comment by louking** [comment]
dup #305?

**Comment by louking** [comment]
see solution for #338 to see if it applies
