### ISSUE TITLE
BacklogLimitExceeded (rabbitmq)

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#305]
Jenny: I think the above error may have occurred ... when I was trying to import the results, but my computer froze midway through and I had to reboot. Once I was up and running again, I went back in and tried to upload the results again, but I don't know if the first upload ever finished processing. At any rate, the next upload seemed to work, and things seemed normal as I was going through the results.

Lou: I had a feeling your computer died during the import. I think what happens is the state is updated with progress, for each result, and updating the state queues a message (using rabbitmq) from the back end (import execution) to the front end (web service) on the server side. The browser asks the front end what the state is periodically which depletes that queue. This last bit is what is updating the progress bar. So if the browser disappears, the queue builds and in this case with so many result entries, fills up.

I cleaned up the queue by rebooting the server between the time you had the problem and the time you didn't. That might have been overkill, but I didn't want to experiment on what is the minimum needed to restart to resolve the issue, and restarting the server only takes a couple of minutes in any case.

Note: the exception seems to happen from the front end, not the back end, but when I had looked at the rabbitmq admin overview (http://scoretility.com:15672/#/), there were at least 6000 messages queued.

```
        Message type:       ERROR
        Location:           /var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py:1587
        Module:             app
        Function:           log_exception
        Time:               2017-05-08 07:40:17,135

        Message:

        Exception on /importresultsstatus/a869555c-8704-4fc2-8bf1-b78fa8db870f [GET]

Traceback (most recent call last):
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/results.py", line 2114, in get
    if task.state == 'PENDING':
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/celery/result.py", line 394, in state
    return self._get_task_meta()['status']
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/celery/result.py", line 339, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/celery/backends/amqp.py", line 180, in get_task_meta
    raise self.BacklogLimitExceeded(task_id)
BacklogLimitExceeded: a869555c-8704-4fc2-8bf1-b78fa8db870f
```

**Comment by louking** [comment]
test file enclosed
[frederickhalf2017.xlsx](https://github.com/louking/rrwebapp/files/987342/frederickhalf2017.xlsx)
