### ISSUE TITLE
exception on reload of edit participants

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#322]
on sandbox created women's distance festival club, series. series doesn't require membership

loaded data from 2014 wdf, and executed edit participants. upon reload of edit participants, got fatal exception

is this regression for series which don't require memberships?

```
       Message type:       ERROR
        Location:           /var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py:1587
        Module:             app
        Function:           log_exception
        Time:               2018-02-14 07:43:09,026

        Message:

        Exception on /editparticipants/27100 [GET]

Traceback (most recent call last):
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/sandbox.scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/results.py", line 593, in get
    memberagegens[thismembername].append({'age': age, 'gender':thismember['gender']})
UnboundLocalError: local variable 'age' referenced before assignment
```

**Comment by louking** [comment]
regression appears to be in https://github.com/louking/rrwebapp/commit/e705549ba1bbb42db4527d435cb64ef3ce2346e4 at result.py https://github.com/louking/rrwebapp/commit/e705549ba1bbb42db4527d435cb64ef3ce2346e4#diff-66d65900285b3bd9c0e66570893e41c2R611

I think maybe need to fill in age when ValueError occurs
