### ISSUE TITLE
importresults: exception when importing new non-member into race

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#332]
[Release 2.7.3 ](https://github.com/louking/rrwebapp/releases/tag/2.7.3)

database from 8/5/2018

Attempting to import csv of enclosed file causes exception. Analysis finds that the record for Erin Reeder caused the exception. 

[1000 m  Results 2018.xlsx](https://github.com/louking/rrwebapp/files/2264166/1000.m.Results.2018.xlsx)

```
Traceback (most recent call last):
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/results.py", line 2199, in importresultstask
    runner_choices = importresults.update_dbresult(fileresult, dbresult)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/results.py", line 379, in update_dbresult
    self.dte.set_dbrow(thisinresult, dbresult)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/datatables_utils.py", line 180, in set_dbrow
    setattr(dbrow, dbattr, callback(inrow))
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/results.py", line 293, in set_initialdisposition
    pastresultage = pastresult.agage
AttributeError: 'NoneType' object has no attribute 'agage'
```

**Comment by louking** [comment]
I'm guessing problem is we have someone who used to be a member but we don't have their birthdate. And we don't have any results to look at to see if her current age is consistent. 

I'm not sure when she was a member or how her record got into this state. We don't have any record of her I can retrieve on runningahead.

![image](https://user-images.githubusercontent.com/875138/43742518-44d2266c-99a0-11e8-9e3c-bb4926ca7432.png)
