### ISSUE TITLE
handle unicode characters in names

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#346]
- https://www.i18nqa.com/debug/table-iso8859-1-vs-windows-1252.html

```
[2019-06-05 13:53:28,730: WARNING/Worker-1] c:\users\lking\anaconda2\Lib\difflib.py:437: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  a[besti+bestsize] == b[bestj+bestsize]:
```

`Error Occurred: Traceback (most recent call last): File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\results.py", line 2205, in importresultstask runner_choices = importresults.update_dbresult(fileresult, dbresult) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\results.py", line 379, in update_dbresult self.dte.set_dbrow(thisinresult, dbresult) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\datatables_utils.py", line 180, in set_dbrow setattr(dbrow, dbattr, callback(inrow)) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\results.py", line 340, in set_initialdisposition missed = filtermissed(club_id,missed,race.date,dbresult.age) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\results.py", line 123, in filtermissed runner = Runner.query.filter_by(club_id=club_id,name=runnername,dateofbirth=ascdob).first() File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\query.py", line 2659, in first ret = list(self[0:1]) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\query.py", line 2457, in __getitem__ return list(res) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\query.py", line 2760, in __iter__ self.session._autoflush() File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\session.py", line 1303, in _autoflush util.raise_from_cause(e) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\session.py", line 1293, in _autoflush self.flush() File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\session.py", line 2019, in flush self._flush(objects) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\session.py", line 2137, in _flush transaction.rollback(_capture_exception=True) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__ compat.reraise(exc_type, exc_value, exc_tb) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\session.py", line 2101, in _flush flush_context.execute() File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute rec.execute(self) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute uow File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\persistence.py", line 174, in save_obj mapper, table, insert) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\orm\persistence.py", line 800, in _emit_insert_statements execute(statement, params) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute return meth(self, multiparams, params) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement compiled_sql, distilled_params File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context context) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception exc_info File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context context) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute cursor.execute(statement, parameters) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\MySQLdb\cursors.py", line 205, in execute self.errorhandler(self, exc, value) File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler raise errorclass, errorvalue OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.OperationalError) (1366, "Incorrect string value: '\\x92brien' for column 'name' at row 1") [SQL: u'INSERT INTO managedresult (club_id, raceid, place, name, fname, lname, gender, age, city, state, hometown, club, time, runnerid, initialdisposition, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (4, 33850, 3075, 'Kathryn O\x92brien', 'Kathryn', 'O\x92brien', 'F', 34, 'Potomac', 'MD', 'Potomac, MD', None, 10371.75, None, '', 1)]`

**Comment by louking** [comment]
Also

```
Message type:       ERROR
Location:           /var/www/scoretility.com/rrwebapp/rrwebapp/views/admin/results.py:1345
Module:             results
Function:           post
Time:               2021-06-20 14:47:02,940
User:              Jenny

Message:

Traceback (most recent call last):
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/views/admin/results.py", line 1311, in post
    rr = RaceResults(resultpathname,race.distance)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/raceresults.py", line 90, in __init__
    self._findhdr()
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/raceresults.py", line 111, in _findhdr
    origline = next(self.file)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/loutilities/textreader.py", line 365, in __next__
    row = next(self.CSV)
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 4676: invalid continuation byte
```

and 

```
Message type:       ERROR
Location:           /var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py:1892
Module:             app
Function:           log_exception
Time:               2021-06-20 10:22:33,114
User:               Mike

Message:

Exception on /doc/importresults [GET]

Traceback (most recent call last):
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/docs.py", line 67, in get
    for row in cc:
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 595: invalid start byte
```

**Comment by louking** [comment]
this problem occurs on linux but not on windows. a locale issue?

see https://stackoverflow.com/questions/35502328/unicodeencodeerror-on-linux-but-not-on-windows

**Comment by louking** [comment]
see https://groups.google.com/g/comp.os.linux.setup/c/kSAWSeb0RWY?pli=1

```
[lking@loutility-server-digitalocean ~]$ locale -m | grep '^CP'
CP10007
CP1125
CP1250
CP1251
CP1252
CP1253
CP1254
CP1255
CP1256
CP1257
CP1258
CP737
CP770
CP771
CP772
CP773
CP774
CP775
CP949
[lking@loutility-server-digitalocean ~]$ echo $LANG
en_US.UTF-8
[lking@loutility-server-digitalocean ~]$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by louking** [comment]
celery task

```
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: File "/var/www/sandbox.scoretility.com/venv/lib64/python3.6/site-packages/celery/bin/celery.py", line 213, in main
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: return celery(auto_envvar_prefix="CELERY")
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: File "/var/www/sandbox.scoretility.com/venv/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: return self.main(*args, **kwargs)
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: File "/var/www/sandbox.scoretility.com/venv/lib64/python3.6/site-packages/click/core.py", line 760, in main
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: _verify_python3_env()
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: File "/var/www/sandbox.scoretility.com/venv/lib64/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: " mitigation steps.{}".format(extra)
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult htt...gation steps.
Jul 22 17:08:57 loutility-server-digitalocean celery[20879]: This system lists a couple of UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: aa_DJ.utf8,...8, ar_KW.utf8
```

**Comment by louking** [comment]
see https://chardet.readthedocs.io/en/latest/usage.html -- maybe convert file to utf-8 on the way in
