### ISSUE TITLE
exception: 'RaceResult' has no attribute 'age'

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#347]
```
        Message type:       ERROR
        Location:           /var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py:1587
        Module:             app
        Function:           log_exception
        Time:               2019-06-06 06:08:10,346

        Message:

        Exception on /_results [GET]

Traceback (most recent call last):
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/request.py", line 321, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/results.py", line 1503, in get
    rowTable = DataTables(request.args, RaceResult, RaceResult.query.filter_by(**resultfilter).join("runner").join("series").filter_by(**seriesfilter).join("race"), columns, dialect='mysql')
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/sqlalchemy_datatables-0.4.1lk3-py2.7.egg/datatables/__init__.py", line 244, in __init__
    self.run()
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/sqlalchemy_datatables-0.4.1lk3-py2.7.egg/datatables/__init__.py", line 298, in run
    self.sorting()
  File "/var/www/scoretility.com/rrwebapp/lib/python2.7/site-packages/sqlalchemy_datatables-0.4.1lk3-py2.7.egg/datatables/__init__.py", line 492, in sorting
    obj = getattr(self.sqla_object, tmp_name)
AttributeError: type object 'RaceResult' has no attribute 'age'
```

`137.200.32.38 - - [06/Jun/2019:06:08:10 -0400] "GET /_results?club=fsrc&draw=3&columns%5B0%5D%5Bdata%5D=name&columns%5B0%5D%5Bname%5D=name&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=Victor+Cretella&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=true&columns%5B1%5D%5Bdata%5D=series&columns%5B1%5D%5Bname%5D=series&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=date&columns%5B2%5D%5Bname%5D=date&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=race&columns%5B3%5D%5Bname%5D=race&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=miles&columns%5B4%5D%5Bname%5D=miles&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=gender&columns%5B5%5D%5Bname%5D=gender&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=age&columns%5B6%5D%5Bname%5D=age&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=genderplace&columns%5B7%5D%5Bname%5D=genderplace&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=division&columns%5B8%5D%5Bname%5D=division&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=divisionplace&columns%5B9%5D%5Bname%5D=divisionplace&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=time&columns%5B10%5D%5Bname%5D=time&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=pace&columns%5B11%5D%5Bname%5D=pace&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=true&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B12%5D%5Bdata%5D=agtime&columns%5B12%5D%5Bname%5D=agtime&columns%5B12%5D%5Bsearchable%5D=true&columns%5B12%5D%5Borderable%5D=true&columns%5B12%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B12%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B13%5D%5Bdata%5D=agpercent&columns%5B13%5D%5Bname%5D=agpercent&columns%5B13%5D%5Bsearchable%5D=true&columns%5B13%5D%5Borderable%5D=true&columns%5B13%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B13%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=6&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1559815661972 HTTP/1.1" 500 291 "https://scoretility.com/results?club=fsrc" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"`

**Comment by louking** [comment]
dup #230
