### ISSUE TITLE
sqlalchemy-datatables 2.0.1 ColumnDT() incompatibility

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#372]
`pip install -U sqlalchemy-datatables (sqlalchemy-datatables-2.0.1)` produces for Edit Participants

```
Traceback (most recent call last):
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\results.py", line 662, in get
    ColumnDT('id',                  mData='id',                   searchable=False),
TypeError: __new__() got an unexpected keyword argument 'searchable'

```

for Results:

```
Traceback (most recent call last):
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\lib\site-packages\flask\views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\request.py", line 185, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\results.py", line 1490, in get
    filter=lambda c: '{0:.{1}f}'.format(c,0 if int(c)==float(c) else 1 if c > 3 else 3 if c < 1 else 2)),
TypeError: __new__() got an unexpected keyword argument 'filter'
```

**Comment by louking** [comment]
Use of TypeDecorator for formatting: https://docs.sqlalchemy.org/en/13/faq/sqlexpressions.html?highlight=string%20format#rendering-bound-parameters-inline
