### ISSUE TITLE
celery load problem 3.1.23

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#447]
amqp-1.4.9 billiard-3.3.0.23 celery-3.1.23 kombu-3.0.37

```
(venv) C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp> c: && cd "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp" && cmd /C ""c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\Scripts\python.exe" c:\Users\lking\.vscode\extensions\ms-python.python-2021.4.765268190\pythonFiles\lib\python\debugpy\launcher 57617 -- -m celery -A rrwebapp.celery worker -c2 -l info -Q longtask "
Traceback (most recent call last):
  File "C:\Users\lking\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lking\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\lking\.vscode\extensions\ms-python.python-2021.4.765268190\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\lking\.vscode\extensions\ms-python.python-2021.4.765268190\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\lking\.vscode\extensions\ms-python.python-2021.4.765268190\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 331, in run_module
    run_module_as_main(target_as_str, alter_argv=True)
  File "C:\Users\lking\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lking\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\celery\__main__.py", line 54, in <module>
    main()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\celery\__main__.py", line 30, in main
    main()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\celery\bin\celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\celery\bin\celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\celery\bin\base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\celery\bin\base.py", line 477, in setup_app_from_commandline
    user_preload = tuple(self.app.user_options['preload'] or ())
AttributeError: 'NoneType' object has no attribute 'user_options'
```

**Comment by louking** [comment]
resolved with https://github.com/louking/rrwebapp/commit/b9af81fce67fd224f94c272ff4614ed468699f56
