### ISSUE TITLE
celery analyzeresultstask: InvalidClientIdError: (invalid_request) Missing parameter: client_id

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#452]
```
Traceback (most recent call last):
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\tasks.py", line 199, in analyzeresultstask
    collectservices[servicename](self, club_id, memberfile, thisdetailfile, status)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\resultsutils.py", line 691, in collect
    self.openservice(club_id)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\runningaheadresults.py", line 103, in openservice
    self.service = runningahead.RunningAhead(debug=True, key=key, secret=secret)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\running\runningahead.py", line 164, in __init__
    data = oauth.fetch_token(token_url='https://api.runningahead.com/oauth2/token', client_id=key, client_secret=secret)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\requests_oauthlib\oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Missing parameter: client_id

```

**Comment by louking** [comment]
see https://github.com/requests/requests-oauthlib/issues/360
