### ISSUE TITLE
import members: from csv, UnicodeDecodeError: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#469]
```
Traceback (most recent call last):
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\tasks.py", line 182, in importmemberstask
    members = clubmember.CsvClubMember(memberpathname)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\clubmember.py", line 374, in __init__
    ClubMember.__init__(self,csvfile,cutoff=cutoff,exceldates=False)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\clubmember.py", line 132, in __init__
    for filerow in IN:
  File "C:\Users\lking\AppData\Local\Programs\Python\Python36\lib\csv.py", line 112, in __next__
    row = next(self.reader)
  File "C:\Users\lking\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6326: character maps to <undefined>

```

**Comment by louking** [comment]
requires iso-8859-1 open for csv file
