### ISSUE TITLE
rrwebapp.wsgi: ImportError: cannot import name 'Celery'

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#480]
```
started with python 3.6.8, GCC 4.8.5 20150623 (Red Hat 4.8.5-44)
mod_wsgi (pid=15889): Failed to exec Python script file '/etc/mod_wsgi-express/sandbox.scoretility.com/handler.wsgi'.
mod_wsgi (pid=15889): Exception occurred processing WSGI script '/etc/mod_wsgi-express/sandbox.scoretility.com/handler.wsgi'.
Traceback (most recent call last):
  File "/etc/mod_wsgi-express/sandbox.scoretility.com/handler.wsgi", line 95, in <module>
    recorder_directory=recorder_directory)
  File "/var/www/sandbox.scoretility.com/venv/lib64/python3.6/site-packages/mod_wsgi/server/__init__.py", line 1471, in __init__
    exec(code, self.module.__dict__)
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp.wsgi", line 41, in <module>
    application = create_app(Production(configfiles), configfiles)
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/__init__.py", line 159, in create_app
    from .views.admin import bp as admin
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/views/admin/__init__.py", line 12, in <module>
    from . import member
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/views/admin/member.py", line 34, in <module>
    from ...tasks import importmemberstask
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/tasks.py", line 16, in <module>
    from celery.utils.log import get_task_logger
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/celery.py", line 9, in <module>
    from celery import Celery
ImportError: cannot import name 'Celery'
```

**Comment by louking** [comment]
wrong working directory was used in /root/bin/init-mod_wsgi-express-uplevel
