### ISSUE TITLE
BuildError: Could not build url for endpoint 'index'

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#488]
```
Message type:       ERROR
Location:           /var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py:1892
Module:             app
Function:           log_exception
Time:               2021-06-07 07:50:55,304
User:               anonymous

Message:

Exception on /viewstandings/ [GET]

Traceback (most recent call last):
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/views/frontend/userviews.py", line 130, in get
    return flask.redirect(flask.url_for('index'))
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'frontend.index' instead?
```

**Comment by louking** [comment]
Note this was possibly the result of a manually formed URL, so maybe isn't urgent for deployment
