### ISSUE TITLE
background task: NotAllowed: Connection.open: (530) NOT_ALLOWED - access to vhost 'scoretility.com' refused for user 'scoretility.www'

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#489]
```
Message type:       ERROR
Location:           /var/www/scoretility.com/rrwebapp/rrwebapp/views/admin/member.py:381
Module:             member
Function:           post
Time:               2021-06-10 15:03:00,542
User:               [jenny]

Message:

Traceback (most recent call last):
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/utils/functional.py", line 32, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/views/admin/member.py", line 371, in post
    task = importmemberstask.apply_async((club_id, tempdir, memberpathname, memberfilename))
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/celery/app/task.py", line 565, in apply_async
    **options
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/celery/app/base.py", line 749, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/celery/app/amqp.py", line 532, in send_task_message
    **properties
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/messaging.py", line 178, in publish
    exchange_name, declare,
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/connection.py", line 525, in _ensured
    return fun(*args, **kwargs)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/messaging.py", line 184, in _publish
    channel = self.channel
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/messaging.py", line 206, in _get_channel
    channel = self._channel = channel()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/utils/functional.py", line 34, in __call__
    value = self.__value__ = self.__contract__()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/messaging.py", line 221, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/connection.py", line 884, in default_channel
    self._ensure_connection(**conn_opts)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/connection.py", line 439, in _ensure_connection
    callback, timeout=timeout
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/utils/functional.py", line 325, in retry_over_time
    return fun(*args, **kwargs)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/connection.py", line 866, in _connection_factory
    self._connection = self._establish_connection()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/connection.py", line 801, in _establish_connection
    conn = self.transport.establish_connection()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/kombu/transport/pyamqp.py", line 128, in establish_connection
    conn.connect()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/amqp/connection.py", line 329, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/amqp/connection.py", line 523, in drain_events
    while not self.blocking_read(timeout):
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/amqp/connection.py", line 529, in blocking_read
    return self.on_inbound_frame(frame)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/amqp/method_framing.py", line 53, in on_frame
    callback(channel, method_sig, buf, None)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/amqp/connection.py", line 536, in on_inbound_method
    method_sig, payload, content,
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/amqp/abstract_channel.py", line 143, in dispatch_method
    listener(*args)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/amqp/connection.py", line 666, in _on_close
    (class_id, method_id), ConnectionError)
amqp.exceptions.NotAllowed: Connection.open: (530) NOT_ALLOWED - access to vhost 'scoretility.com' refused for user 'scoretility.www'
```

**Comment by louking** [comment]
see loutility-server-digitalocean-log.txt 2021-06-10 17:19
