### ISSUE TITLE
importresultstask: AttributeError: 'datetime.time' object has no attribute 'strip'

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#490]
```
Traceback (most recent call last):
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/tasks.py", line 108, in importresultstask
    next(rr)
  File "/var/www/sandbox.scoretility.com/rrwebapp/rrwebapp/raceresults.py", line 347, in __next__
    if 'time' not in result or result['time'].strip() == '':
AttributeError: 'datetime.time' object has no attribute 'strip'
```

**Comment by louking** [comment]
test escape: test file used had text times rather than native excel times
