### ISSUE TITLE
viewstandings: StopIteration exception

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#501]
```
2021-07-06 16:37:08,215 INFO:127.0.0.1 - - [06/Jul/2021 16:37:08] "GET /viewstandings/?club=mddcgp&year=2021&series=Maryland%2FDC%20Grand%20Prix&desc=Maryland%2FDC%20Grand%20Prix%20-%202021%20Maryland%2FDC%20Grand%20Prix HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\views\frontend\userviews.py", line 178, in get
    rr.renderseries(fh)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\renderstandings.py", line 1428, in renderseries
    racenum = next(iracenums)
StopIteration
2021-07-06 16:37:08,253 ERROR:Error on request:
Traceback (most recent call last):
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\views\frontend\userviews.py", line 178, in get
    rr.renderseries(fh)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\renderstandings.py", line 1428, in renderseries
    racenum = next(iracenums)
StopIteration
```

**Comment by louking** [comment]
In Germantown 5M results, similar result wasn't confirmed. Consequently Skip Sensxxxx ended up in the results twice, which caused the StopIteration exception.

Should verify that runner isn't in the results multiple times?
