### ISSUE TITLE
edit participants view: draw exception AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#502]
searched for similar on germantown 5 miler 2021, then removed similar filter

```
2021-07-07 12:18:51,299 INFO:127.0.0.1 - - [07/Jul/2021 12:18:51] "GET /admin/_editparticipants/51587?draw=5&columns%5B0%5D%5Bdata%5D=&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=place&columns%5B1%5D%5Bname%5D=place&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=resultname&columns%5B2%5D%5Bname%5D=resultname&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=gender&columns%5B3%5D%5Bname%5D=gender&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=age&columns%5B4%5D%5Bname%5D=age&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=disposition&columns%5B5%5D%5Bname%5D=disposition&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=true&columns%5B6%5D%5Bdata%5D=membertype&columns%5B6%5D%5Bname%5D=membertype&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=confirm&columns%5B7%5D%5Bname%5D=confirm&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=runnerid&columns%5B8%5D%5Bname%5D=runnerid&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=hometown&columns%5B9%5D%5Bname%5D=hometown&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=club&columns%5B10%5D%5Bname%5D=club&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=time&columns%5B11%5D%5Bname%5D=time&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=true&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=1&order%5B0%5D%5Bdir%5D=asc&start=0&length=-1&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1625674658533 HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\views\admin\results.py", line 317, in get
    tableselects[r.id] = getrunnerchoices(club_id, race, pool, r)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\resultsutils.py", line 165, in getrunnerchoices
    nameage = '{} ({})'.format(runner.name, age(racedatedt,dobdt))
AttributeError: 'NoneType' object has no attribute 'name'
2021-07-07 12:18:51,323 ERROR:Error on request:
Traceback (most recent call last):
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "c:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\venv\lib\site-packages\flask\views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\views\admin\results.py", line 317, in get
    tableselects[r.id] = getrunnerchoices(club_id, race, pool, r)
  File "C:\Users\lking\Documents\Lou's Software\projects\rrwebapp\rrwebapp\rrwebapp\resultsutils.py", line 165, in getrunnerchoices
    nameage = '{} ({})'.format(runner.name, age(racedatedt,dobdt))
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by louking** [comment]
could not reproduce
