### ISSUE TITLE
2013 decathlon is causing exception

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#513]
races do exist, and have been imported, seems a regression

```
2021-07-30 18:28:01,012 ERROR: anonymous Exception on /viewstandings/ [GET] [in /var/www/scoretility.com/venv/lib64/python3.6/site-\
packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/views/frontend/userviews.py", line 187, in get
    rr.renderseries(fh)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/renderstandings.py", line 1453, in renderseries
    self.collectstandings(racesprocessed, gen, race.id, byrunner, divrunner)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/renderstandings.py", line 1305, in collectstandings
    divdate = tYmd.asc2dt(earlyresult.race.date)
AttributeError: 'NoneType' object has no attribute 'race'
2021-07-30 18:28:01,923 INFO: anonymous 73.128.176.172: GET http://scoretility.com/viewstandings/?club=fsrc&year=2013&series=decath\
lon&desc=Frederick%20Steeplechasers%20Running%20Club%20-%202013%20decathlon 500 [in /var/www/scoretility.com/rrwebapp/rrwebapp/__in\
it__.py:222]
```

**Comment by louking** [comment]
Investigation showed that there were several RaceResult records for which there are no ManagedResult records. Not sure how this came to be in that state, but a workaround is possible.
