### ISSUE TITLE
import members: UnicodeDecodeError: \'utf-8\' codec can\'t decode byte 0xec in position 4539: invalid continuation byte

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#525]
On windows development system only.

```
[2021-12-01 06:04:09,018: INFO/SpawnPoolWorker-2] Task rrwebapp.tasks.importmemberstask[4bb4cd34-8abc-4453-9d57-647f2ad7e3d0] succeeded in 180.65600000019185s: {'current': 100, 'total': 100, 'traceback': 'Traceback (most recent call last):
  File "C:\Users\lking\Documents\Lou\'s Software\projects\rrwebapp\rrwebapp\rrwebapp\tasks.py", line 182, in importmemberstask
    members = clubmember.CsvClubMember(memberpathname)
  File "C:\Users\lking\Documents\Lou\'s Software\projects\rrwebapp\rrwebapp\rrwebapp\clubmember.py", line 377, in __init__
    ClubMember.__init__(self,csvfile,cutoff=cutoff,exceldates=False)
  File "C:\Users\lking\Documents\Lou\'s Software\projects\rrwebapp\rrwebapp\rrwebapp\clubmember.py", line 135, in __init__
    for filerow in IN:
  File "C:\Users\lking\AppData\Local\Programs\Python\Python36\lib\csv.py", line 119, in __next__
    row = next(self.reader)
  File "C:\Users\lking\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: \'utf-8\' codec can\'t decode byte 0xec in position 4539: invalid continuation byte
```

**Comment by louking** [comment]
now seeing the following when race imported

```
Error Occurred: C:\\Users\\lking\\Documents\\Lou's Software\\projects\\rrwebapp\\uploads\2_mile_Results_2021_copy_-_fixed.csv: could not find fields ['place'] in header ['\ufeffPlace', 'First Name', 'Last Name', 'Age', 'Sex', 'time']
```
