### ISSUE TITLE
download results view: give better error message for missing result set

### ISSUE THREAD

**Issue by louking** [louking/rrwebapp#567]
```
Message type:       ERROR
Location:           /var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py:1892
Module:             app
Function:           log_exception
Time:               2022-07-02 15:06:16,264
User:               xxxxx@xxxxxxxx.xxx

Message:

Exception on /admin/downloadresults [POST]

Traceback (most recent call last):
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/scoretility.com/venv/lib64/python3.6/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/views/admin/results.py", line 2075, in post
    newheading = [headers[r] for r in rsuheading]
  File "/var/www/scoretility.com/rrwebapp/rrwebapp/views/admin/results.py", line 2075, in <listcomp>
    newheading = [headers[r] for r in rsuheading]
KeyError: 'result_id'
```

**Comment by louking** [comment]
https://github.com/louking/rrwebapp/commit/78208f5c62a7f8228aff53c78b6830e3f218fd51
